substitutions:
  friendly_name: 'Hot Air Station Smart Plug'
  name: 'hot_air_station_smart_plug'

packages:
  device-base: !include packages/device-base.esp.yaml
  athom-smart-plug-v2: !include
    file: packages/athom-smart-plug-v2.esp.yaml
    vars:
      power_sensor_update_frequency: 4s

switch:
  - id: !extend relay
    restore_mode: ALWAYS_OFF
    on_turn_on:
      then:
        - component.update: tool_state
    on_turn_off:
      then:
        - component.update: tool_state

text_sensor:
  - platform: template
    name: 'Tool State'
    id: tool_state
    update_interval: 10s
    lambda: |-
      if (!id(relay).state) {
        return {"off"};
      } else if (id(power_sensor).state < 12) { // W
        return {"standby"};
      } else { // >= 12W
        return {"running"};
      }
