substitutions:
  friendly_name: Living Room Radar
  name: living_room_radar

packages:
  esp32-base: !include packages/esp32-base.esp.yaml
  supermini: !include packages/esp32c3-supermini.esp.yaml
  mm-wave-presence: !include packages/mm-wave-presence.esp.yaml
