substitutions:
  friendly_name: 'Office Primary Plug'
  name: 'office_primary_plug'

packages:
  device-base: !include packages/device-base.esp.yaml
  s31-switch: !include packages/s31-switch.esp.yaml

switch:
  - id: !extend relay
    restore_mode: ALWAYS_ON
