substitutions:
  friendly_name: Office Radar
  name: office_radar

packages:
  device-base: !include packages/device-base.esp.yaml
  supermini: !include packages/esp32c3-supermini.esp.yaml
  mm-wave-presence: !include packages/mm-wave-presence.esp.yaml
