substitutions:
 friendly_name: Oven Sensor Suite
 name: oven_sensor_suite

packages:
 esp32-base: !include packages/esp32-base.esp.yaml
 esp32s3-zero: !include packages/esp32s3-zero.esp.yaml

spi:
 clk_pin: 8
 miso_pin: 9

sensor:
 - platform: max31855
   name: "Oven Thermocouple"
   id: oven_temperature
   cs_pin: 7
   update_interval: 1s
