substitutions:
  friendly_name: Scratch Device
  name: scratch_device

packages:
  esp32-base: !include packages/esp32-base.esp.yaml
  esp32c3-supermini: !include packages/esp32c3-supermini.esp.yaml

logger:
  level: debug

sensor:
  - platform: adc
    id: usb_voltage
    name: "A2 Voltage"
    pin: 4
    attenuation: auto
    update_interval: 1s

binary_sensor:
  - platform: gpio
    id: is_usb_active
    pin: 3
