substitutions:
  friendly_name: Theoretical Thermostat Display
  name: theoretical_thermostat_display
  thermostat_display_id: hx8394_panel
  thermostat_touchscreen_id: hx8394_touch


packages:
  esp32-base: !include packages/esp32-base.esp.yaml
  p4-nano: !include packages/esp32-p4-nano.esp.yaml
  p4-nano-audio: !include packages/esp32-p4-nano/audio.esp.yaml
  p4-nano-media-player: !include packages/esp32-p4-nano/audio-speaker-media-player.esp.yaml
  display: !include packages/display-hx8394.esp.yaml
  thermostat-ui: !include packages/thermostat/display-ui.esp.yaml

esphome:
  on_boot:
    - priority: 700
      then:
        - script.execute: enable_mipi_phy
    - priority: 800
      then:
        - light.turn_on:
            id: display_backlight
            brightness: !lambda 'return id(backlight_night_mode) ? 0.7f : 1.0f;'

logger:
  level: DEBUG
