substitutions:
  friendly_name: Theoretical Thermostat Display
  name: thermostat_display

packages:
  esp32-base: !include packages/esp32-base.esp.yaml
  ble-beacon-tracker: !include packages/ble-beacon-tracker.esp.yaml
  t-panel-s3: !include packages/t-panel-s3.esp.yaml

esphome:
  on_boot:
    then:
      - light.turn_on:
          id: display_backlight
          brightness: 90%

image:
  - file: mdi:power
    id: power
    type: grayscale
    transparency: alpha_channel
    resize: 36x36
  - file: mdi:snowflake
    id: snowflake
    type: grayscale
    transparency: alpha_channel
    resize: 36x36
  - file: mdi:fire
    id: fire
    type: grayscale
    transparency: alpha_channel
    resize: 36x36
  - file: mdi:fan
    id: fan
    type: grayscale
    transparency: alpha_channel
    resize: 36x36
  - file: mdi:weather-night
    id: clear_night
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-cloudy
    id: cloudy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-fog
    id: fog
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-hail
    id: hail
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-lightning
    id: lightning
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-lightning-rainy
    id: lightning_rainy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-partly-cloudy
    id: partlycloudy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-pouring
    id: pouring
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-rainy
    id: rainy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-snowy
    id: snowy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-snowy-rainy
    id: snowy_rainy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-sunny
    id: sunny
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-windy
    id: windy
    type: grayscale
    transparency: alpha_channel
    resize: 28x28
  - file: mdi:weather-windy-variant
    id: windy_variant
    type: grayscale
    transparency: alpha_channel
    resize: 28x28

font:
  - file: gfonts://Figtree@600
    id: cur_temp_font
    size: 72
    bpp: 4
    glyphs: [
      0123456789,°
    ]
  - file: gfonts://Figtree@500
    id: top_bar_weather
    size: 25
    bpp: 4
  - file: gfonts://Figtree@300
    id: top_bar_lighter
    size: 22
    bpp: 8
  - file: gfonts://Figtree@500
    id: top_bar_emph
    size: 22
    bpp: 4

display:
  - id: !extend rgb_display
    update_interval: 1s
    auto_clear_enabled: True
    lambda: |-
      auto warming_color = Color(0xe1, 0x75, 0x2e);
      auto cooling_color = Color(0x27, 0x76, 0xcc);
      auto top_bar_color = Color(0xc0, 0xc0, 0xc0);
      auto icon_bar_color = Color(0xda, 0xda, 0xda);
      auto black = Color(0x00, 0x00, 0x00);
      auto blurred_temp_color = Color(0x30, 0x30, 0x30);

      int baseline = id(cur_temp_font).get_baseline();

      int set_top = 4;
      it.image(8, set_top + 1, id(sunny), ImageAlign::TOP_LEFT, top_bar_color, black);
      it.print(8 + id(sunny).get_width() + 4, set_top, id(top_bar_weather), top_bar_color, TextAlign::LEFT, "16°");

      int roomTempX = it.get_width() - 2;
      int roomTempLeft, roomTempTop, _w, _h;
      it.get_text_bounds(roomTempX, set_top + 2, " 19°", id(top_bar_emph), TextAlign::RIGHT, &roomTempLeft, &roomTempTop, &_w, &_h);
      it.print(roomTempX, set_top + 2, id(top_bar_emph), top_bar_color, TextAlign::RIGHT, "19°");
      it.print(roomTempLeft, set_top + 2, id(top_bar_lighter), top_bar_color, TextAlign::RIGHT, "Living Room");

      int cur_inset = 50;
      int cur_top = 176;
      it.print(cur_inset, cur_top, id(cur_temp_font), cooling_color, TextAlign::LEFT, "23°");
      it.print(it.get_width() - cur_inset, cur_top, id(cur_temp_font), blurred_temp_color, TextAlign::RIGHT, "19°");
      it.filled_rectangle(0, cur_top + baseline, it.get_width(), it.get_height() - 140, cooling_color);


      int icon_bar_top = it.get_height() - 32 - 30;
      int icon_bar_width = 210;

      it.image((it.get_width() - icon_bar_width) / 2, icon_bar_top, id(snowflake), ImageAlign::TOP_LEFT, icon_bar_color, cooling_color);
      it.image(it.get_width() / 2, icon_bar_top, id(power), ImageAlign::TOP_CENTER, icon_bar_color, cooling_color);
      it.image((it.get_width() + icon_bar_width) / 2, icon_bar_top, id(fan), ImageAlign::TOP_RIGHT, icon_bar_color, cooling_color);
