substitutions:
  friendly_name: Theoretical Thermostat Scratch
  name: thermostat_climate_scratch

packages:
  esp32-base: !include packages/esp32-base.esp.yaml
  esp32s3-zero: !include packages/esp32s3-zero.esp.yaml

web_server:
  port: 80
  version: 3


binary_sensor:
  - platform: gpio
    pin:
      number: 1
      mode: INPUT_PULLDOWN
    name: "Binary Input 1"
    id: binary_input_1
  - platform: gpio
    pin:
      number: 2
      mode: INPUT_PULLDOWN
    name: "Binary Input 2"
    id: binary_input_2
  - platform: gpio
    pin:
      number: 3
      mode: INPUT_PULLDOWN
    name: "Binary Input 3"
    id: binary_input_3
