substitutions:
  # The bus used to communicate with the HX8394 PMIC
  mipi_bus: mipi_bus

i2c_device:
  - id: hx8394_pmic
    i2c_id: ${mipi_bus}
    address: 0x45

output:
  - platform: template
    id: brightness_command_output
    type: float
    inverted: True
    write_action:
     - lambda: !lambda id(hx8394_pmic).write_byte(0x96, (uint8_t)(255.0 * (1.0 - state)));

light:
  - platform: monochromatic
    id: display_backlight
    name: '${friendly_name} Backlight'
    output: brightness_command_output
    default_transition_length: 250ms
    restore_mode: ALWAYS_OFF

script:
  - id: enable_mipi_phy
    then:
      - lambda: |-
          id(hx8394_pmic).write_byte(0x95, 0x11);
          id(hx8394_pmic).write_byte(0x95, 0x17);
      - light.turn_off:
          id: display_backlight
      - delay: 100ms
      - light.turn_on:
          id: display_backlight
          brightness: 100%

touchscreen:
  - platform: gt911
    id: hx8394_touch
    i2c_id: ${mipi_bus}
    address: 0x5D
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false
    on_release:
      then:
        - script.execute: resume_display_for_interaction

display:
  # NOTE that when used with LVGL, its byte_order must be set to little_endian
  - platform: mipi_dsi
    id: hx8394_panel
    model: CUSTOM
    dimensions:
      width: 720
      height: 1280
    color_order: rgb
    pixel_mode: 16bit
    color_depth: 16
    lanes: 2
    lane_bit_rate: 700Mbps
    pclk_frequency: 58MHz
    hsync_pulse_width: 20
    hsync_back_porch: 20
    hsync_front_porch: 40
    vsync_pulse_width: 4
    vsync_back_porch: 10
    vsync_front_porch: 24
    reset_pin: 27
    show_test_card: false
    auto_clear_enabled: false
    init_sequence:
      - [0xB9, 0xFF, 0x83, 0x94]
      - [0xB1, 0x48, 0x0A, 0x6A, 0x09, 0x33, 0x54, 0x71, 0x71, 0x2E, 0x45]
      - [0xBA, 0x61, 0x03, 0x68, 0x6B, 0xB2, 0xC0]
      - [0xB2, 0x00, 0x80, 0x64, 0x0C, 0x06, 0x2F]
      - [0xB4, 0x1C, 0x78, 0x1C, 0x78, 0x1C, 0x78, 0x01, 0x0C, 0x86, 0x75, 0x00, 0x3F, 0x1C, 0x78, 0x1C, 0x78, 0x1C, 0x78, 0x01, 0x0C, 0x86]
      - [0xD3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x08, 0x32, 0x10, 0x05, 0x00, 0x05, 0x32, 0x13, 0xC1, 0x00, 0x01, 0x32, 0x10, 0x08, 0x00, 0x00, 0x37, 0x03, 0x07, 0x07, 0x37, 0x05, 0x05, 0x37, 0x0C, 0x40]
      - [0xD5, 0x18, 0x18, 0x18, 0x18, 0x22, 0x23, 0x20, 0x21, 0x04, 0x05, 0x06, 0x07, 0x00, 0x01, 0x02, 0x03, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x19, 0x19, 0x19, 0x19]
      - [0xD6, 0x18, 0x18, 0x19, 0x19, 0x21, 0x20, 0x23, 0x22, 0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x05, 0x04, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x19, 0x19, 0x18, 0x18]
      - [0xE0, 0x07, 0x08, 0x09, 0x0D, 0x10, 0x14, 0x16, 0x13, 0x24, 0x36, 0x48, 0x4A, 0x58, 0x6F, 0x76, 0x80, 0x97, 0xA5, 0xA8, 0xB5, 0xC6, 0x62, 0x63, 0x68, 0x6F, 0x72, 0x78, 0x7F, 0x7F, 0x00, 0x02, 0x08, 0x0D, 0x0C, 0x0E, 0x0F, 0x10, 0x24, 0x36, 0x48, 0x4A, 0x58, 0x6F, 0x78, 0x82, 0x99, 0xA4, 0xA0, 0xB1, 0xC0, 0x5E, 0x5E, 0x64, 0x6B, 0x6C, 0x73, 0x7F, 0x7F]
      - [0xCC, 0x0B]
      - [0xC0, 0x1F, 0x73]
      - [0xB6, 0x6B, 0x6B]
      - [0xD4, 0x02]
      - [0xBD, 0x01]
      - [0xB1, 0x00]
      - [0xBD, 0x00]
      - [0xBF, 0x40, 0x81, 0x50, 0x00, 0x1A, 0xFC, 0x01]
      - [0x3A, 0x50] # COLMOD
      - [0x11]
      - delay 200ms
      - [0xB2, 0x00, 0x80, 0x64, 0x0C, 0x06, 0x2F, 0x00, 0x00, 0x00, 0x00, 0xC0, 0x18]
      - [0x29]
      - delay 80ms
