# https://www.waveshare.com/esp32-p4-nano.htm

esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM

esp32:
  variant: ESP32P4
  cpu_frequency: 360MHZ
  flash_size: 16MB
  framework:
    type: esp-idf
    # version: 5.5.1
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"
      CONFIG_LWIP_MAX_SOCKETS: '16'
      CONFIG_SPIRAM_XIP_FROM_PSRAM: n
    advanced:
      enable_idf_experimental_features: true

logger:
  baud_rate: 115200
  hardware_uart: UART0

psram:
  speed: 200MHz
  mode: hex

esp_ldo:
  - id: mipi_phy_ldo
    channel: 3
    voltage: 2.5V

# This bus is used to communicate with the display's PMIC early in the boot
# process, to have things powered and ready by the time display init begins
i2c:
  - id: mipi_bus
    sda: 7
    scl: 8
    frequency: 100kHz

# The ESP32-P4 does not have radios, so requires a coprocessor for Wifi/Bluetooth
esp32_hosted:
  variant: ESP32C6
  reset_pin: 54
  cmd_pin: 19
  clk_pin: 18
  d0_pin: 14
  d1_pin: 15
  d2_pin: 16
  d3_pin: 17
  active_high: true

output:
  - platform: ledc
    pin: 26
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    id: display_backlight
    output: backlight_pwm
    name: '${friendly_name} Backlight'
    default_transition_length: 250ms
    restore_mode: RESTORE_DEFAULT_ON
