external_components:
  - source: github://shyndman/esphome-cst3240
    components: [cst3240]

esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio
    build_unflags: -Werror=all

esp32:
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_PERF: y

psram:
  mode: quad
  speed: 80MHz

i2c:
  scan: True
  sda: 17
  scl: 18
  frequency: 400kHz

xl9535:
  - id: io_hub
    address: 0x20

spi:
  interface: software
  clk_pin:
    xl9535: io_hub
    number: 15
  mosi_pin:
    xl9535: io_hub
    number: 16

output:
  - platform: ledc
    pin: 14
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    id: display_backlight
    output: backlight_pwm
    name: '${friendly_name} Backlight'
    default_transition_length: 250ms
    restore_mode: RESTORE_DEFAULT_ON

touchscreen:
  - platform: cst3240
    id: rgb_display_touchscreen
    interrupt_pin: 21
    update_interval: 20ms
    display: rgb_display
    reset_pin:
      xl9535: io_hub
      number: 4
    calibration:
      x_min: 0
      x_max: 478
      y_min: 0
      y_max: 478
    on_release:
      then:
        - if:
            condition: lvgl.is_paused
            then:
              - logger.log:
                  level: DEBUG
                  format: '[idle] LVGL resuming'
              - lvgl.resume:
              - lvgl.widget.redraw:
              - light.turn_on: display_backlight
        - if:
            condition:
              lambda: 'return id(switch_antiburn).state;'
            then:
              - switch.turn_off: switch_antiburn

display:
  - platform: mipi_rgb
    id: rgb_display
    model: T-PANEL-S3
    reset_pin:
      xl9535: io_hub
      number: 5
    auto_clear_enabled: false
    show_test_card: false
